name: Pipeline Docker - Entrega Contínua

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build da Imagem Docker
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do GitHub
        uses: actions/checkout@v4

      - name: Construir imagem Docker
        run: docker build -t wilzinho/docker-teste:latest .

  test:
    name: Teste da Imagem Docker Hub
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Baixar código do GitHub
        uses: actions/checkout@v4

      - name: Baixar imagem do Docker Hub
        run: docker pull wilzinho/docker-teste:latest

      - name: Verificar imagem
        run: docker images

      - name: Executar container
        run: docker run -d --name meu-container -p 8080:80 wilzinho/docker-teste:latest

      - name: Verificar container
        run: docker ps

      - name: Testar NGINX
        run: |
          sleep 5
          curl --fail http://localhost:8080

      - name: Verificar resposta HTTP
        run: curl --head --fail http://localhost:8080

```
